FROM node:16.14.0-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VERSION
ENV VERSION=${VERSION}
RUN echo "version=${VERSION}" > ./version.txt
RUN echo "const http = require('http'); http.createServer(function (req, res) { res.write('IP address: ' + req.connection.remoteAddress + '<br>'); res.write('Hostname: ' + require('os').hostname() + '<br>'); res.write('Version: ' + process.env.VERSION + '<br>'); res.end();}).listen(8080);" > server.js
EXPOSE 8080
CMD ["node", "server.js"]

# Etap 2 - Tworzenie obrazu produkcyjnego
FROM nginx:latest
COPY --from=build /app/version.txt /usr/share/nginx/html/
COPY --from=build /app/server.js /usr/share/nginx/html/
HEALTHCHECK --interval=5s --timeout=3s CMD curl --fail http://localhost:8080 || exit 1